# Build and publish a release of Playmaster using semantic-release whenever
# changes are merged into master.
name: "🎉 Release"

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types:
      - completed
    branches:
      - master

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install @semantic-release/exec @google/semantic-release-replace-plugin @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make sem-release

      # In ".releaserc.yaml" a step is defined to write the release version to
      # ".version.txt" upon successful release. This step checks to see if that
      # exists to determine if the other jobs need to run.
      - id: status
        name: Set release status
        shell: bash
        run: |
          if [ -f .version.txt ]; then
            echo "was_released=yes" >> "$GITHUB_OUTPUT"
          else
            echo "was_released=no" >> "$GITHUB_OUTPUT"
          fi

    outputs:
      should_publish: ${{ steps.status.outputs.was_released }}

  publish-to-copr:
    name: 🟤 Publish to COPR
    needs: release
    if: ${{ needs.release.outputs.should_publish == 'yes' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger COPR Build
        run: curl -X POST ${{ secrets.COPR_WEBHOOK_URL }}
